version: '3.4'

services:
  authdemoblazor.webui:
    image: ${DOCKER_REGISTRY-}authdemoblazorwebui
    build:
      context: .
      dockerfile: AuthDemoBlazor.WebUI/AuthDemoBlazor.WebUI/Dockerfile
    depends_on:
      authdemoblazor.db-sqlserver:
        condition: service_started
  authdemoblazor.db-sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: AuthDemoBlazor.DB-SQLServer
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_DATABASE=AuthDemoBlazor
    volumes:
      - vmyvol:/app
    ports:
     - "1433:1433"
volumes:
  vmyvol: